default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: p0stgr3s
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: persons_development

test:
  <<: *default
  database: persons_test